complete -c efd_contribuicoes -s g -l generate -d 'Gera o arquivo de auto-complete para o shell especificado (bash, zsh, fish, etc)' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c efd_contribuicoes -s r -l range -d 'Selecione arquivos SPED EFD para analisar especificando o intervalo' -r
complete -c efd_contribuicoes -s c -l clear_terminal -d 'Limpa a tela do terminal antes de apresentar a análise'
complete -c efd_contribuicoes -s d -l debug -d 'Ativar mensagens de debug (ex: detalhes de correlações do Bloco M)'
complete -c efd_contribuicoes -s e -l excluir-saidas -d 'Exclui itens de operações de SAÍDA dos arquivos finais (Excel/CSV).'
complete -c efd_contribuicoes -s t -l excluir-cst-49 -d 'Excluir CST 49 do Rateio da Receita Bruta.'
complete -c efd_contribuicoes -s f -l find -d 'Listar arquivos SPED EFD encontrados no diretório atual.'
complete -c efd_contribuicoes -s o -l operacoes-de-creditos -d 'Retém apenas itens que geram crédito (50 <= CST <= 66).'
complete -c efd_contribuicoes -s p -l csv -d 'Gerar arquivo CSV.'
complete -c efd_contribuicoes -s n -l no-excel -d 'Desativar a geração do arquivo Excel (.xlsx).'
complete -c efd_contribuicoes -s h -l help -d 'Print help (see more with \'--help\')'
complete -c efd_contribuicoes -s V -l version -d 'Print version'
